val appCompileSdkVersion by extra(37)
val appTargetSdkVersion by extra(36)
val appMinSdkVersion by extra(24)
val appJdkVersion by extra(21)
val appVersionCode by extra(39)
val appVersionName by extra("1.0.6")
