import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.artifacts.VersionCatalogsExtension
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

class KotlinCommonConventionPlugin : Plugin<Project> {
    override fun apply(target: Project) {
        val appJdkVersion = target.intProperty("appJdkVersion")
        val kotlinVersion = target.libsVersion("kotlin")

        target.configurations.configureEach {
            resolutionStrategy.eachDependency {
                if (requested.group == "org.jetbrains.kotlin" && requested.name == "kotlin-metadata-jvm") {
                    useVersion(kotlinVersion)
                    because("Kotlin processors must read metadata generated by the configured Kotlin compiler.")
                }
            }
        }

        target.tasks.withType(KotlinCompile::class.java).configureEach {
            compilerOptions.jvmTarget.set(
                org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget(appJdkVersion.toString())
            )
        }
    }
}

private fun Project.intProperty(name: String): Int =
    (rootProject.extensions.extraProperties[name] as Number).toInt()

private fun Project.libsVersion(name: String): String =
    rootProject.extensions
        .getByType(VersionCatalogsExtension::class.java)
        .named("libs")
        .findVersion(name)
        .get()
        .requiredVersion
