import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.artifacts.VersionCatalogsExtension
import org.gradle.api.tasks.testing.Test
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

class KotlinCommonConventionPlugin : Plugin<Project> {
    override fun apply(target: Project) {
        val appJdkVersion = target.intProperty("appJdkVersion")
        val kotlinVersion = target.libsVersion("kotlin")

        listOf("com.android.application", "com.android.library").forEach { pluginId ->
            target.pluginManager.withPlugin(pluginId) {
                target.tasks.withType(Test::class.java).configureEach {
                    // Robolectric 4.17's FileDescriptor interceptor needs this on JDK 17+.
                    // Test JVM only: https://robolectric.org/getting-started/#running-with-java-17-and-higher
                    jvmArgs("--add-opens=java.base/jdk.internal.access=ALL-UNNAMED")
                }
            }
        }

        target.configurations.configureEach {
            resolutionStrategy.eachDependency {
                if (requested.group == "org.jetbrains.kotlin" && requested.name == "kotlin-metadata-jvm") {
                    useVersion(kotlinVersion)
                    because("Kotlin processors must read metadata generated by the configured Kotlin compiler.")
                }
            }
        }

        target.tasks.withType(KotlinCompile::class.java).configureEach {
            compilerOptions.jvmTarget.set(
                org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget(appJdkVersion.toString())
            )
        }
    }
}

private fun Project.intProperty(name: String): Int =
    (rootProject.extensions.extraProperties[name] as Number).toInt()

private fun Project.libsVersion(name: String): String =
    rootProject.extensions
        .getByType(VersionCatalogsExtension::class.java)
        .named("libs")
        .findVersion(name)
        .get()
        .requiredVersion
